### ISSUE TITLE
find_largest_angle_interval crash

### ISSUE THREAD

**Issue by SpitfireX** [Windfisch/agario-frickel#9]
Traceback (most recent call last):
File "D:\Projekte\Programmieren\GitHub\agario-frickel\main.py", line 49, in <module> target = strategy.process_frame()
File "D:\Projekte\Programmieren\GitHub\agario-frickel\strategy.py", line 60, in process_frame(a,b) = find_largest_angle_interval(allowed_intervals)
File "D:\Projekte\Programmieren\GitHub\agario-frickel\interval_utils.py", line 41, in find_largest_angle_interval
if (intervals[0][0]==0 and intervals[-1][1]==2*pi):
IndexError: list index out of range

This happens regularly and I am not sure why.

**Comment by Windfisch** [comment]
this happens when there's no allowed interval, i.e. we're encircled by
enemy cells.

we should probably provide some fallback in cases where no runaway
direction could be found

**Comment by Windfisch** [comment]
worked around in commit 8a1591c08, but only with a really dumb fallback direction: 0 deg
